// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
  show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9I6_RGsJDUue65XdIKH2bEUQz8rNwbT4',
    appId: '1:896592650203:web:5815f58fd95038347491fe',
    messagingSenderId: '896592650203',
    projectId: 'wateny',
    authDomain: 'wateny.firebaseapp.com',
    storageBucket: 'wateny.firebasestorage.app',
    measurementId: 'G-CQLH65GRM1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBs4x187shxWMCjjd15ej6IKM9R-qy-YGE',
    appId: '1:896592650203:ios:31e2b99413b2af137491fe',
    messagingSenderId: '896592650203',
    projectId: 'wateny',
    storageBucket: 'wateny.firebasestorage.app',
    iosBundleId: 'com.example.socialNetworkApp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBs4x187shxWMCjjd15ej6IKM9R-qy-YGE',
    appId: '1:896592650203:ios:31e2b99413b2af137491fe',
    messagingSenderId: '896592650203',
    projectId: 'wateny',
    storageBucket: 'wateny.firebasestorage.app',
    iosBundleId: 'com.example.socialNetworkApp',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDa_pthPZvBaO4lOf8JFw4vJpvJFo318cI',
    appId: '1:896592650203:android:331a465624c10b567491fe',
    messagingSenderId: '896592650203',
    projectId: 'wateny',
    storageBucket: 'wateny.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9I6_RGsJDUue65XdIKH2bEUQz8rNwbT4',
    appId: '1:896592650203:web:805839ba740482af7491fe',
    messagingSenderId: '896592650203',
    projectId: 'wateny',
    authDomain: 'wateny.firebaseapp.com',
    storageBucket: 'wateny.firebasestorage.app',
    measurementId: 'G-TP1F7V6MH5',
  );

}